### ISSUE TITLE
Bug: Errors when running clients on Linux in AP 0.4.1

### ISSUE THREAD

**Issue by CubeTheThird** [ArchipelagoMW/Archipelago#1840]
### What happened?

When running various clients on Linux (downloaded with the tar.gz package), the following stacktrace is produced:

```
﻿[root at 2023-05-27 14:01:34,066]: Archipelago (0.4.1) logging initialized on Linux-6.3.3-arch1-1-x86_64-with-glibc2.37 running Python 3.9.16
[root at 2023-05-27 14:01:34,617]: Could not load world WorldSource(stardew_valley.apworld, is_zip=True):
Traceback (most recent call last):
  File "worlds/__init__.py", line 68, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/rules.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/locations.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/data/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/data/crops_data.py", line 45, in <module>
  File "worlds/stardew_valley/data/crops_data.py", line 26, in load_crop_csv
  File "importlib/resources.py", line 147, in files
  File "importlib/resources.py", line 49, in _get_package
  File "importlib/resources.py", line 40, in _resolve
  File "importlib/__init__.py", line 118, in import_module
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "worlds/__init__.py", line 68, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/rules.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/locations.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/data/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/stardew_valley/data/crops_data.py", line 45, in <module>
  File "worlds/stardew_valley/data/crops_data.py", line 26, in load_crop_csv
  File "importlib/resources.py", line 147, in files
  File "importlib/resources.py", line 49, in _get_package
  File "importlib/resources.py", line 40, in _resolve
  File "importlib/__init__.py", line 118, in import_module
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Additionally, with the Link's Awakening client, I get this message, though I am unsure if this is related:

```
[Client at 2023-05-27 14:01:34,788]: Uncaught exception
Traceback (most recent call last):
  File "__startup__.py", line 135, in run
  File "console.py", line 18, in run
  File "LinksAwakeningClient.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "worlds/ladx/Locations.py", line 91, in <module>
  File "worlds/AutoWorld.py", line 77, in __new__
Exception: Name conflict on Logic Mixin LinksAwakeningLogic trying to overwrite rupees
```

### What were the expected results?

The clients to run without errors.

### Software

Local generation

**Comment by black-sliver** [comment]
It looks like both issues are tied to python3.9 and older. I pinged the world devs on discord, but in the meantime those builds should work around the problems: https://github.com/ArchipelagoMW/Archipelago/actions/runs/5103816452

Note that there is a problem in the LADX Client on non-windows where it does not show a GUI unless RetroArch is running in addition to your two reports. Maybe @zig-for to good measure

**Comment by CubeTheThird** [comment]
Yes, that all seems to work great, thank you! And you are correct about the GUI issue, but that's easy to work around.
