### ISSUE TITLE
Bug: Two KH2 unit tests fail on my machine despite passing in CI

### ISSUE THREAD

**Issue by Ixrec** [ArchipelagoMW/Archipelago#2624]
### What happened?

<img width="340" alt="image" src="https://github.com/ArchipelagoMW/Archipelago/assets/5285357/54926eb5-f969-4cb2-b81f-71da8e28cd03">

clicking on `test_default_without_LnD` shows:
```

Failure
Traceback (most recent call last):
  File "C:\Users\j-pop\git\Archipelago\worlds\kh2\test\test_form_logic.py", line 109, in test_default_without_LnD
    self.assertFalse((self.can_reach_location(levels[2])), levels[2])
AssertionError: True is not false : Valor level 4


```

clicking on `test_just_a_form_connections` shows:
```

Error
Traceback (most recent call last):
  File "C:\Users\j-pop\git\Archipelago\worlds\kh2\test\test_form_logic.py", line 160, in test_just_a_form_connections
    allPossibleForms.remove(ItemName.FinalForm)
ValueError: list.remove(x): x not in list

```

I can reproduce this consistently on both today's latest `main` commit, and a weeks-old `main` commit.

### What were the expected results?

Tests pass, matching CI

### Software

Local generation

**Comment by nicholassaylor** [comment]
Are you able to recreate this on main? I wasn't able to get these failures.

**Comment by Exempt-Medic** [comment]
@Ixrec

**Comment by Ixrec** [comment]
This doesn't happen to me on current main.
