### ISSUE TITLE
Bug: Client traceback when using `[size=small]`

### ISSUE THREAD

**Issue by Eijebong** [ArchipelagoMW/Archipelago#2741]
### What happened?

We discovered that the client supported some markup during a run today. Someone tried using a client (TextClient, BizhawkClient, LADX Client) `[size=small]` and we all got the following traceback:

```
Uncaught Exception:
Traceback (most recent call last):
  File "kivy/_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/uix/label.py", line 424, in texture_update
    self._label.refresh()
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/__init__.py", line 823, in refresh
    sz = self.render()
         ^^^^^^^^^^^^^
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/markup.py", line 141, in render
    ret = self._pre_render()
          ^^^^^^^^^^^^^^^^^^
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/markup.py", line 210, in _pre_render
    size = int(item)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'small'
```

### What were the expected results?

I would expect a proper error to be displayed instead of that traceback.

### Software

While playing

**Comment by black-sliver** [comment]
Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/3659
Will be in the next release.
