### ISSUE TITLE
Bug: Sending a message with too big of a size crashes text clients

### ISSUE THREAD

**Issue by Eijebong** [ArchipelagoMW/Archipelago#2743]
### What happened?

After discovering that `[size]` was a thing, someone (*cough* me *cough*) sent a `[size=50000]hi` message. Which crashed clients.

 ```
 Uncaught exception
Exception: Unable to allocate memory for texture (size is -1597768288)
stderr: Exception: Unable to allocate memory for texture (size is -1597768288)
stderr: Exception ignored in: 'kivy.graphics.texture.Texture.allocate'
stderr: Traceback (most recent call last):
stderr:   File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/uix/label.py", line 427, in texture_update
stderr:     self._label.texture.bind()
stderr: Exception: Unable to allocate memory for texture (size is -1597768288)
Uncaught Exception:
Traceback (most recent call last):
  File "kivy/_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/uix/label.py", line 427, in texture_update
    self._label.texture.bind()
  File "kivy/graphics/texture.pyx", line 765, in kivy.graphics.texture.Texture.bind
  File "kivy/graphics/texture.pyx", line 790, in kivy.graphics.texture.Texture.bind
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/__init__.py", line 815, in _texture_fill
    self.render(real=True)
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/markup.py", line 143, in render
    ret = self._render_real()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/__init__.py", line 742, in _render_real
    data = self._render_end()
           ^^^^^^^^^^^^^^^^^^
  File "/home/eijebong/code/ap_emerald/.venv/lib/python3.11/site-packages/kivy/core/text/text_sdl2.py", line 50, in _render_end
    return self._surface.get_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "kivy/core/text/_text_sdl2.pyx", line 157, in kivy.core.text._text_sdl2._SurfaceContainer.get_data
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

### What were the expected results?

I would expect clients to not crash when that happens. Maybe add an upper bound to the size?

### Software

While playing

**Comment by black-sliver** [comment]
Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/3659
Will be in the next release.
