### ISSUE TITLE
Bug: Generator nor server app work

### ISSUE THREAD

**Issue by sssillies** [ArchipelagoMW/Archipelago#3301]
### What happened?

When i open the either apps, it shows some lines of code then closes, atleast the server app generates logs
heres the full log
`[root at 2024-05-14 18:16:50,836]: Archipelago (0.3.6) logging initialized.
[root at 2024-05-14 18:16:51,706]: Uncaught exception
Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 16, in run
  File "MultiServer.py", line 2163, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "MultiServer.py", line 2111, in main
  File "MultiServer.py", line 202, in __init__
  File "MultiServer.py", line 207, in _load_game_data
  File "worlds\__init__.py", line 51, in <module>
  File "C:\ProgramData\Archipelago\lib\worlds\ultrakill.apworld\ultrakill\__init__.py", line 8, in <module>
    from .Options import UltrakillOptions, Goal, UnlockType, StartingWeapon
  File "C:\ProgramData\Archipelago\lib\worlds\ultrakill.apworld\ultrakill\Options.py", line 2, in <module>
    from Options import Choice, Range, Toggle, DefaultOnToggle, DeathLink, PerGameCommonOptions
ImportError: cannot import name 'PerGameCommonOptions' from 'Options' (C:\ProgramData\Archipelago\lib\library.zip\Options.pyc)`

### What were the expected results?

The ArchipelagoServer to make servers and for ArchipelagoGenerator to generate the files

### Software

Local generation

**Comment by ScipioWright** [comment]
It sounds to me like you have a severely outdated version of Archipelago. Please update to the latest release, which you can find here: https://github.com/ArchipelagoMW/Archipelago/releases/tag/0.4.6

In the future, it is recommended that you put posts like this in the tech-support channel on the discord instead of raising an issue on the github.

**Comment by ScipioWright** [comment]
I'm going to close this issue now. If you need further help, please head to the Archipelago discord and make a post in the tech-support channel. If for some reason you are unable to do so, you can reopen this issue. I don't think that's disallowed, just discouraged.
