### ISSUE TITLE
OoT item link key/song bugs

### ISSUE THREAD

**Issue by Alchav** [ArchipelagoMW/Archipelago#453]
Attempting to item link keys or songs if they are set to be in the OoT game's dungeons or song locations causes an error when it attempts to place these items and remove them from the item pool, as item link has already removed them.

**Comment by Ijwu** [comment]
What is the error? Is a stack trace available from the console? Is there a YAML or set of YAMLs you can provide for reproduction?

**Comment by Alchav** [comment]
YAML:
`name: ItemLinkTest
game:
  Ocarina of Time: 1
Ocarina of Time:
  item_links:
    [{item_pool: ["Small Key (Water Temple)"], replacement_item: "Recovery Heart", name: "OoT Item Link"}]`

Error:
`Traceback (most recent call last):
  File "__startup__.py", line 113, in run
  File "Console.py", line 15, in run
  File "Generate.py", line 668, in <module>
  File "Generate.py", line 214, in main
  File "Main.py", line 227, in main
  File "worlds\AutoWorld.py", line 62, in call_all
  File "worlds\AutoWorld.py", line 55, in call_single
  File "worlds\oot\__init__.py", line 605, in pre_fill
ValueError: list.remove(x): x not in list`

**Comment by Ijwu** [comment]
@espeon65536 thoughts?
