### ISSUE TITLE
OoT item link hint bug 

### ISSUE THREAD

**Issue by Alchav** [ArchipelagoMW/Archipelago#454]
When trying to generate an OoT game with all items item-linked, if in-game hints are not turned off an error occurs while attempting to generate hints

**Comment by Alchav** [comment]
YAML:
```
name: ItemLinkTest
game:
  Ocarina of Time: 1
Ocarina of Time:
  shuffle_mapcompass: keysanity
  shuffle_smallkeys: keysanity
  shuffle_fortresskeys: keysanity
  shuffle_bosskeys: keysanity
  shuffle_ganon_bosskey: keysanity
  shuffle_song_items: any
  item_links:
    [{item_pool: ["Everything"], replacement_item: "Recovery Heart", name: "OoT Item Link"}]
```
Error:
```
Traceback (most recent call last):
  File "__startup__.py", line 113, in run
  File "Console.py", line 15, in run
  File "Generate.py", line 668, in <module>
  File "Generate.py", line 214, in main
  File "Main.py", line 416, in main
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "worlds\AutoWorld.py", line 55, in call_single
  File "worlds\oot\__init__.py", line 779, in generate_output
  File "worlds\oot\Hints.py", line 646, in buildWorldGossipHints
KeyError: 2
```
