### ISSUE TITLE
WebHost.py seems to have a dependency on the Zelda rom

### ISSUE THREAD

**Issue by JarnoWesthof** [ArchipelagoMW/Archipelago#490]
There seems to be some incorrect depencies, or its not handled very cleanly

C:\Users\Jarno\Desktop\AP>WebHost.py
[2022-05-07 10:21:49,148] [Errno 2] No such file or directory: 'C:\\Users\\Jarno\\Desktop\\AP\\Zelda no Densetsu - Kamigami no Triforce (Japan).sfc'
Traceback (most recent call last):
  File "C:\Users\Jarno\Desktop\AP\WebHost.py", line 60, in <module>
    update_sprites_lttp()
  File "C:\Users\Jarno\Desktop\AP\WebHostLib\lttpsprites.py", line 36, in update_sprites_lttp
    sprite = Sprite(os.path.join(input_dir, file))
  File "C:\Users\Jarno\Desktop\AP\worlds\alttp\Rom.py", line 514, in __init__
    self.get_vanilla_sprite_data()
  File "C:\Users\Jarno\Desktop\AP\worlds\alttp\Rom.py", line 546, in get_vanilla_sprite_data
    base_rom_bytes = bytes(read_rom(open(file_name, "rb")))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jarno\\Desktop\\AP\\Zelda no Densetsu - Kamigami no Triforce (Japan).sfc'
[2022-05-07 10:21:49,179] Could not update LttP sprites.
[2022-05-07 10:21:50,132] Serving on http://0.0.0.0:80

It should probably not throw an error there just mention maybe mention that the sprites could not updated as the file was not found

**Comment by Berserker66** [comment]
Yes, intentional. Its a warning with trace.

**Comment by JarnoWesthof** [comment]
Why not a normal clean message? anyway if its intentional i guess we can close this issue

**Comment by Berserker66** [comment]
The traceback could be suppressed and you'd just get "Could not update LttP sprites."
The webhost is not really run by users anyway, as a developer-oriented tool giving said developers a traceback makes the most sense to me.
